-- Create support_messages table
BEGIN;

CREATE TABLE IF NOT EXISTS public.support_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  category text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  email text NOT NULL,
  user_id uuid NULL
);

CREATE INDEX IF NOT EXISTS support_messages_created_at_idx ON public.support_messages (created_at DESC);

COMMIT;
