
  create table "public"."resources" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "title" text not null,
    "type" text not null,
    "excerpt" text,
    "content" text,
    "author" text default 'MyFutureAbroad Team'::text,
    "cover_image" text,
    "tags" text[],
    "reading_time_minutes" integer,
    "published" boolean default false,
    "featured" boolean default false
      );


CREATE UNIQUE INDEX resources_pkey ON public.resources USING btree (id);

alter table "public"."resources" add constraint "resources_pkey" PRIMARY KEY using index "resources_pkey";

grant delete on table "public"."resources" to "anon";

grant insert on table "public"."resources" to "anon";

grant references on table "public"."resources" to "anon";

grant select on table "public"."resources" to "anon";

grant trigger on table "public"."resources" to "anon";

grant truncate on table "public"."resources" to "anon";

grant update on table "public"."resources" to "anon";

grant delete on table "public"."resources" to "authenticated";

grant insert on table "public"."resources" to "authenticated";

grant references on table "public"."resources" to "authenticated";

grant select on table "public"."resources" to "authenticated";

grant trigger on table "public"."resources" to "authenticated";

grant truncate on table "public"."resources" to "authenticated";

grant update on table "public"."resources" to "authenticated";

grant delete on table "public"."resources" to "service_role";

grant insert on table "public"."resources" to "service_role";

grant references on table "public"."resources" to "service_role";

grant select on table "public"."resources" to "service_role";

grant trigger on table "public"."resources" to "service_role";

grant truncate on table "public"."resources" to "service_role";

grant update on table "public"."resources" to "service_role";


  create policy "Enable read access for all users"
  on "public"."resources"
  as permissive
  for select
  to public
using (true);



