create table if not exists resources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  type text not null, -- e.g., 'guide', 'article'
  excerpt text,
  content text, -- Markdown content
  author text default 'MyFutureAbroad Team',
  cover_image text,
  tags text[],
  reading_time_minutes integer,
  published boolean default false,
  featured boolean default false
);

create policy "Enable read access for all users" on "public"."resources"
as permissive for select
to public
using (true);
