export interface Visa {
	id: number;
	name: string;
	visa_type: string;
	description: string;
	target_applicant?: string;
	application_fee_usd: number;
	application_fee_amount?: number;
	application_fee_currency?: string;
	base_currency?: string;
	processing_time_days: number;
	processing_time_min_days?: number;
	processing_time_max_days?: number;
	validity_months?: number;
	renewable?: boolean;
	renewal_conditions?: string;
	country_id: number;
	benefits?: string[];
	min_age?: number;
	max_age?: number;
	min_income?: number;
	min_income_currency?: string;
	min_savings?: number;
	min_savings_currency?: string;
	required_skills?: string[];
	eligible_nationalities?: string[];
	excluded_nationalities?: string[];
	requires_health_insurance?: boolean;
	requires_clean_criminal_record?: boolean;
	work_permitted?: boolean | null;
	dependants_allowed?: boolean | null;
	has_path_to_residency?: boolean;
	path_to_residency_description?: string;
	required_documents?: string[];
	application_process_steps?: string[];
	tax_implications?: string;
	official_link?: string;
	image_url?: string;
	additional_info?: any;
}

export default {} as any;
