-- Run this FIRST in Supabase SQL Editor
-- Temporarily disable RLS for data seeding
ALTER TABLE IF EXISTS countries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS visas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_countries DISABLE ROW LEVEL SECURITY;

-- Clear existing data to avoid conflicts
TRUNCATE TABLE visas RESTART IDENTITY CASCADE;
TRUNCATE TABLE countries RESTART IDENTITY CASCADE;
