-- Run this LAST in Supabase SQL Editor
-- Re-enable RLS after seeding
ALTER TABLE IF EXISTS countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS visas ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS services ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS service_countries ENABLE ROW LEVEL SECURITY;
